export enum BaseCategory {
  BasicFoods = "Basic Foods",
  FrozenProducts = "Frozen Products",
  MilkDairyProducts = "Milk & Dairy Products",
  Breakfast = "Breakfast",
  CheeseColdCuts = "Cheese & Cold Cuts",
  Bakery = "Bakery",
  MeatPoultry = "Meat & Poultry",
  VegetablesFruits = "Vegetables & Fruits",
  BeautyProducts = "Beauty Products",
  PersonalCare = "Personal Care",
  BabyCare = "Baby Care",
  PetCare = "Pet Care",
  CoffeeTea = "Coffee & Tea",
  Beverages = "Beverages",
  Snacks = "Snacks",
  Other = "other",
}

export const categories: string[] = [
  BaseCategory.BasicFoods,
  BaseCategory.FrozenProducts,
  BaseCategory.MilkDairyProducts,
  BaseCategory.Breakfast,
  BaseCategory.CheeseColdCuts,
  BaseCategory.Bakery,
  BaseCategory.MeatPoultry,
  BaseCategory.VegetablesFruits,
  BaseCategory.BeautyProducts,
  BaseCategory.PersonalCare,
  BaseCategory.BabyCare,
  BaseCategory.PetCare,
  BaseCategory.CoffeeTea,
  BaseCategory.Beverages,
  BaseCategory.Snacks,
  BaseCategory.Other,
];

export const categoryTranslations: { [key in BaseCategory]: string } = {
  [BaseCategory.BasicFoods]: "الأطعمة الأساسية",
  [BaseCategory.FrozenProducts]: "المنتجات المجمدة",
  [BaseCategory.MilkDairyProducts]: "الحليب ومنتجات الألبان",
  [BaseCategory.Breakfast]: "الإفطار",
  [BaseCategory.CheeseColdCuts]: "الأجبان واللحوم الباردة",
  [BaseCategory.Bakery]: "المخبوزات",
  [BaseCategory.MeatPoultry]: "اللحوم والدواجن",
  [BaseCategory.VegetablesFruits]: "الخضروات والفواكه",
  [BaseCategory.BeautyProducts]: "منتجات التجميل",
  [BaseCategory.PersonalCare]: "العناية الشخصية",
  [BaseCategory.BabyCare]: "العناية بالطفل",
  [BaseCategory.PetCare]: "العناية بالحيوانات الأليفة",
  [BaseCategory.CoffeeTea]: "القهوة والشاي",
  [BaseCategory.Beverages]: "المشروبات",
  [BaseCategory.Snacks]: "الوجبات الخفيفة",
  [BaseCategory.Other]: "أخرى",
};

export const categoryToIdMap: { [key in BaseCategory]: number } = {
  [BaseCategory.BasicFoods]: 1,
  [BaseCategory.FrozenProducts]: 2,
  [BaseCategory.MilkDairyProducts]: 3,
  [BaseCategory.Breakfast]: 4,
  [BaseCategory.CheeseColdCuts]: 5,
  [BaseCategory.Bakery]: 6,
  [BaseCategory.MeatPoultry]: 7,
  [BaseCategory.VegetablesFruits]: 8,
  [BaseCategory.BeautyProducts]: 9,
  [BaseCategory.PersonalCare]: 10,
  [BaseCategory.BabyCare]: 11,
  [BaseCategory.PetCare]: 12,
  [BaseCategory.CoffeeTea]: 13,
  [BaseCategory.Beverages]: 14,
  [BaseCategory.Snacks]: 15,
  [BaseCategory.Other]: 16,
};
export const idToCategoryMap: { [key: number]: BaseCategory } = {
  1: BaseCategory.BasicFoods,
  2: BaseCategory.FrozenProducts,
  3: BaseCategory.MilkDairyProducts,
  4: BaseCategory.Breakfast,
  5: BaseCategory.CheeseColdCuts,
  6: BaseCategory.Bakery,
  7: BaseCategory.MeatPoultry,
  8: BaseCategory.VegetablesFruits,
  9: BaseCategory.BeautyProducts,
  10: BaseCategory.PersonalCare,
  11: BaseCategory.BabyCare,
  12: BaseCategory.PetCare,
  13: BaseCategory.CoffeeTea,
  14: BaseCategory.Beverages,
  15: BaseCategory.Snacks,
  16: BaseCategory.Other,
};
